# -*- coding: utf-8 -*-
"""In_Class_Activity_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/achiarello630/CSC101/blob/main/In_Class_Activity_1.ipynb

##Instructions for In Class Activity 1

You must find all errors in your scripts. But because you are communicating with a machine, not a person, you have to be exact: the computer cannot understand you at all if there are errors, bugs, in your code. Or the computer may do exactly what you wrote, but not what you meant to do.

Add a comment to the file that describes what you did.

Change the file name to "your name In Class Activity 1" and hand in these corrected Python scripts!

Question 1
"""

x = 15
y = 5
z = 3
y= 15
k = x / y
print(k)

"""Question 2"""

x = 10
y = 20
z = 30
print(x,y,z)

"""Question 3"""

# This program converts miles to km

miles =10
multiplier =1.609344
km = miles * multiplier
print(km)

"""Question 4"""

x = 1
y = 10
z = 2
t = 15
print((x * t) / (y / z))
print('Done')

"""Question 5"""

fruit = "kiwi"
print(fruit, fruit, fruit)