# -*- coding: utf-8 -*-
"""Anthony Chiarello In Class assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXNEVySPtNrl7Alwq6p6A8GBk8P5G2kh
"""

base=10
height=4
print(1/2*base*height)

fenceLength=50
gardenPerimeter=80
print(fenceLength*gardenPerimeter/15)
print("it would take 267 fences to enclose the garden")

total = 835
dollars = total // 100
remaining = total % 100

quarters = remaining // 25
remaining = remaining % 25

dimes = remaining // 10

output = f"Total Amount: {total} cents\nDollars: {dollars}\nQuarters: {quarters}\nDimes: {dimes}"
print(output)

print("One\n\tTwo\n\t\tThree")

first_name= input('Enter your first name:')
print("'John', is a common name.")

Filepath="C:\\Users\\Documents\\MyFlie.txt"
print(Filepath)