# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKmOy2F1g92UatfLTS_OG7ovqilXcSid
"""

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

initializeTurtle()

import ColabTurtle.Turtle as turtle
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(45)

import ColabTurtle.Turtle as turtle


for _ in range(8):
    turtle.forward(100)
    turtle.left(45)

import ColabTurtle.Turtle as turtle

turtle.color("blue")

turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)

import ColabTurtle.Turtle as turtle
turtle.color("blue")

for _ in range(5):
    turtle.forward(100)
    turtle.right(144)

import ColabTurtle.Turtle as turtle

star_turtle1 = turtle
star_turtle1.color("blue")

for _ in range(5):
    star_turtle1.forward(100)
    star_turtle1.right(144)

star_turtle2 = turtle
star_turtle2.color("red")
star_turtle2.penup()
star_turtle2.goto(120, 0)
star_turtle2.pendown()

for _ in range(5):
    star_turtle2.forward(100)
    star_turtle2.right(144)

import ColabTurtle.Turtle as turtle

def draw_star(turtle, color, x, y, size=100):
    turtle.color(color)
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()

    for _ in range(5):
        turtle.forward(size)
        turtle.right(144)
for i, (color, x, y) in enumerate([("blue", 0, 0), ("red", 120, 0)]):
    star_turtle = turtle
    draw_star(star_turtle, color, x, y)

initializeTurtle()

turtle.color("red")
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)

import ColabTurtle.Turtle as turtle

turtle.initializeTurtle()

turtle.color("red")

for _ in range(4):
    turtle.forward(200)
    turtle.left(90)

for i in [1,2,3,]:
  print(" *"*i)