# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18c0sPz1o2CfpNy8heoJhggb66wfArJmz
"""

def display_info():
    title = "Wonder"
    author = "R. J. Palacio"
    description = ("'Wonder is a story about a ten-year-old boy named August Pullman who has facial differences. Wonder is about August's first year of school as a fifth-grade student at Beecher Prep.")

    print("Favorite Book:")
    print(f"Title: {title}")
    print(f"Author: {author}")
    print("Description:", description)

display_info()

def attractions_london():
    """top attractions in London."""
    print("Top Attractions in London:")
    print("- The British Museum")
    print("- The Tower of London")
    print("- Buckingham Palace")
    print("- London Eye")
    print("- Big Ben and the Houses of Parliament")
    print()

def attractions_paris():
    """top attractions in Paris."""
    print("Top Attractions in Paris:")
    print("- Eiffel Tower")
    print("- Louvre Museum")
    print("- Notre-Dame Cathedral")
    print("- Montmartre and Sacré-Cœur Basilica")
    print("- Seine River Cruises")
    print()

def attractions_new_york():
    """top attractions in New York."""
    print("Top Attractions in New York:")
    print("- Statue of Liberty")
    print("- Central Park")
    print("- Times Square")
    print("- Empire State Building")
    print("- The Metropolitan Museum of Art")
    print()

attractions_london()
attractions_paris()
attractions_new_york()

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

initializeTurtle()

import ColabTurtle.Turtle as turtle

def draw_square():
    side_length = 100

    for _ in range(4):
        turtle.forward(side_length)
        turtle.right(90)

turtle.color("blue")

draw_square()

import ColabTurtle.Turtle as turtle

def draw_square():
    side_length = 100

    for _ in range(4):
        turtle.forward(side_length)
        turtle.right(90)
turtle.color("blue")
for i in range(3):
    draw_square()
    turtle.penup()
    turtle.forward(150)
    turtle.pendown()

def find_even_numbers():
    even_numbers = []
    for num in range(11):
        if num % 2 == 0:
            even_numbers.append(num)

    print("Even numbers between 0 and 10:", even_numbers)

find_even_numbers()